version: 2
updates:
- package-ecosystem: nuget
  directory: "/src"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Audit.NET
    versions:
    - 16.5.5
  - dependency-name: Audit.WebApi.Core
    versions:
    - 16.5.0
    - 16.5.5
